### ISSUE TITLE
Multiple nineslice assets from same atlas defaults to first used

### ISSUE THREAD

**Issue by DannyT** [jdotrjs/phaser3-nineslice#11] opened 2018-07-08 10:53 UTC
```
this.first9slice = this.add.nineslice(
    100, 100,
    100, 100,
     {
         key:'atlas',
         frame: 'first-box.png'
     },
    10
);

this.second9slice = this.add.nineslice(
    300, 100,
    100, 100,
     {
         key:'atlas',
         frame: 'second-box.png'
     },
    10
);
```

In this example, both boxes will currently use the first's texture frame.

**Comment by jdotrjs** [comment] 2018-07-21 23:03
Woo. I feel super clever; I had actually already identified this as a potentially issue. Closing as a dupe of https://github.com/jdotrjs/phaser3-nineslice/issues/6

**Closed by jdotrjs** 2018-07-21 23:03 UTC
Labels: bug
